[package]
name = "nomi-mail"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
resvg = { version = "0.45", default-features = false }
lettre = { version = "0.11", default-features = false, features = ["builder", "hostname", "smtp-transport", "tokio1", "tokio1-rustls-tls"] }
thiserror = "1"
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
